import type { AttackDefinition, CharacterDefinition, PlayerAttackKind } from './types';

const requiredAnimationStates: CharacterDefinition['animationStates'] = [
  'idle',
  'walk',
  'run',
  'jump',
  'fall',
  'light-combo-1',
  'light-combo-2',
  'light-combo-3',
  'heavy',
  'air-attack',
  'grab',
  'throw',
  'special',
  'hurt',
  'knockdown',
  'recovery',
  'victory',
];

const attack = (
  id: string,
  kind: PlayerAttackKind,
  damage: number,
  knockbackX: number,
  knockbackY: number,
  hitstopMs: number,
  timings: {
    startupMs: number;
    activeMs: number;
    recoveryMs: number;
    cancelOpenMs: number;
    cancelCloseMs: number;
  },
  extra: Partial<AttackDefinition> = {},
): AttackDefinition => ({
  id,
  kind,
  damage,
  knockbackX,
  knockbackY,
  hitstopMs,
  startupMs: timings.startupMs,
  activeMs: timings.activeMs,
  recoveryMs: timings.recoveryMs,
  cancelOpenMs: timings.cancelOpenMs,
  cancelCloseMs: timings.cancelCloseMs,
  juggleCost: 1,
  groundBounce: false,
  hitbox: {
    offsetX: 54,
    offsetY: -26,
    width: 84,
    height: 78,
  },
  specialGain: 12,
  ...extra,
});

const heavyBrawler: CharacterDefinition = {
  id: 'heavy-brawler',
  displayName: 'Toro',
  archetype: 'heavy-brawler',
  palette: [0xf56f5c, 0x2d2f44, 0xffc857],
  stats: {
    maxHp: 1_300,
    attack: 42,
    defense: 24,
    walkSpeed: 180,
    runSpeed: 280,
    jumpForce: 700,
    gravity: 1_900,
    maxJuggle: 2,
  },
  moveset: {
    'light-1': attack('toro-l1', 'light-1', 35, 300, 20, 55, {
      startupMs: 85,
      activeMs: 100,
      recoveryMs: 170,
      cancelOpenMs: 95,
      cancelCloseMs: 210,
    }),
    'light-2': attack('toro-l2', 'light-2', 42, 330, 35, 60, {
      startupMs: 90,
      activeMs: 90,
      recoveryMs: 180,
      cancelOpenMs: 100,
      cancelCloseMs: 220,
    }),
    'light-3': attack('toro-l3', 'light-3', 58, 410, 90, 70, {
      startupMs: 100,
      activeMs: 90,
      recoveryMs: 220,
      cancelOpenMs: 0,
      cancelCloseMs: 0,
    }),
    heavy: attack(
      'toro-heavy',
      'heavy',
      80,
      520,
      130,
      80,
      {
        startupMs: 160,
        activeMs: 120,
        recoveryMs: 260,
        cancelOpenMs: 0,
        cancelCloseMs: 0,
      },
      { groundBounce: true, juggleCost: 2, specialGain: 18 },
    ),
    air: attack(
      'toro-air',
      'air',
      48,
      310,
      80,
      65,
      {
        startupMs: 110,
        activeMs: 140,
        recoveryMs: 170,
        cancelOpenMs: 0,
        cancelCloseMs: 0,
      },
      { hitbox: { offsetX: 42, offsetY: -4, width: 92, height: 70 } },
    ),
    grab: attack(
      'toro-grab',
      'grab',
      12,
      0,
      0,
      50,
      {
        startupMs: 90,
        activeMs: 60,
        recoveryMs: 140,
        cancelOpenMs: 0,
        cancelCloseMs: 0,
      },
      { hitbox: { offsetX: 30, offsetY: -24, width: 68, height: 90 } },
    ),
    throw: attack(
      'toro-throw',
      'throw',
      78,
      550,
      180,
      95,
      {
        startupMs: 80,
        activeMs: 80,
        recoveryMs: 240,
        cancelOpenMs: 0,
        cancelCloseMs: 0,
      },
      { groundBounce: true, juggleCost: 2 },
    ),
    special: attack(
      'toro-special',
      'special',
      135,
      620,
      210,
      100,
      {
        startupMs: 220,
        activeMs: 210,
        recoveryMs: 360,
        cancelOpenMs: 0,
        cancelCloseMs: 0,
      },
      {
        groundBounce: true,
        juggleCost: 3,
        hitbox: { offsetX: 56, offsetY: -40, width: 140, height: 130 },
        specialGain: 0,
      },
    ),
  },
  animationStates: requiredAnimationStates,
};

const technical: CharacterDefinition = {
  id: 'technical',
  displayName: 'Navaja',
  archetype: 'technical',
  palette: [0x3fd5c6, 0x1f2d3d, 0xf0f4f8],
  stats: {
    maxHp: 1_050,
    attack: 33,
    defense: 18,
    walkSpeed: 220,
    runSpeed: 340,
    jumpForce: 760,
    gravity: 1_850,
    maxJuggle: 3,
  },
  moveset: {
    'light-1': attack('nav-l1', 'light-1', 26, 210, 15, 55, {
      startupMs: 70,
      activeMs: 80,
      recoveryMs: 120,
      cancelOpenMs: 80,
      cancelCloseMs: 180,
    }),
    'light-2': attack('nav-l2', 'light-2', 28, 230, 20, 55, {
      startupMs: 78,
      activeMs: 90,
      recoveryMs: 130,
      cancelOpenMs: 82,
      cancelCloseMs: 190,
    }),
    'light-3': attack('nav-l3', 'light-3', 32, 280, 60, 60, {
      startupMs: 86,
      activeMs: 92,
      recoveryMs: 160,
      cancelOpenMs: 0,
      cancelCloseMs: 0,
    }),
    heavy: attack('nav-heavy', 'heavy', 54, 360, 95, 75, {
      startupMs: 130,
      activeMs: 100,
      recoveryMs: 210,
      cancelOpenMs: 150,
      cancelCloseMs: 210,
    }),
    air: attack('nav-air', 'air', 30, 240, 120, 60, {
      startupMs: 85,
      activeMs: 135,
      recoveryMs: 140,
      cancelOpenMs: 0,
      cancelCloseMs: 0,
    }),
    grab: attack(
      'nav-grab',
      'grab',
      10,
      0,
      0,
      50,
      {
        startupMs: 70,
        activeMs: 65,
        recoveryMs: 120,
        cancelOpenMs: 0,
        cancelCloseMs: 0,
      },
      { hitbox: { offsetX: 30, offsetY: -20, width: 64, height: 88 } },
    ),
    throw: attack(
      'nav-throw',
      'throw',
      52,
      430,
      150,
      85,
      {
        startupMs: 70,
        activeMs: 70,
        recoveryMs: 180,
        cancelOpenMs: 0,
        cancelCloseMs: 0,
      },
      { juggleCost: 2 },
    ),
    special: attack(
      'nav-special',
      'special',
      100,
      450,
      170,
      95,
      {
        startupMs: 185,
        activeMs: 180,
        recoveryMs: 290,
        cancelOpenMs: 0,
        cancelCloseMs: 0,
      },
      { juggleCost: 3, hitbox: { offsetX: 50, offsetY: -34, width: 130, height: 120 } },
    ),
  },
  animationStates: requiredAnimationStates,
};

const agile: CharacterDefinition = {
  id: 'agile',
  displayName: 'Chispa',
  archetype: 'agile',
  palette: [0x73f26f, 0x13293d, 0xf4d35e],
  stats: {
    maxHp: 930,
    attack: 27,
    defense: 14,
    walkSpeed: 255,
    runSpeed: 400,
    jumpForce: 840,
    gravity: 1_820,
    maxJuggle: 4,
  },
  moveset: {
    'light-1': attack('chi-l1', 'light-1', 20, 180, 10, 50, {
      startupMs: 55,
      activeMs: 70,
      recoveryMs: 100,
      cancelOpenMs: 70,
      cancelCloseMs: 170,
    }),
    'light-2': attack('chi-l2', 'light-2', 22, 200, 20, 52, {
      startupMs: 60,
      activeMs: 70,
      recoveryMs: 105,
      cancelOpenMs: 72,
      cancelCloseMs: 176,
    }),
    'light-3': attack('chi-l3', 'light-3', 24, 220, 55, 55, {
      startupMs: 66,
      activeMs: 75,
      recoveryMs: 120,
      cancelOpenMs: 90,
      cancelCloseMs: 170,
    }),
    heavy: attack('chi-heavy', 'heavy', 40, 300, 85, 70, {
      startupMs: 98,
      activeMs: 90,
      recoveryMs: 160,
      cancelOpenMs: 120,
      cancelCloseMs: 170,
    }),
    air: attack('chi-air', 'air', 26, 220, 135, 58, {
      startupMs: 70,
      activeMs: 130,
      recoveryMs: 120,
      cancelOpenMs: 0,
      cancelCloseMs: 0,
    }),
    grab: attack(
      'chi-grab',
      'grab',
      8,
      0,
      0,
      45,
      {
        startupMs: 62,
        activeMs: 60,
        recoveryMs: 95,
        cancelOpenMs: 0,
        cancelCloseMs: 0,
      },
      { hitbox: { offsetX: 22, offsetY: -18, width: 62, height: 84 } },
    ),
    throw: attack('chi-throw', 'throw', 44, 380, 130, 80, {
      startupMs: 62,
      activeMs: 72,
      recoveryMs: 150,
      cancelOpenMs: 0,
      cancelCloseMs: 0,
    }),
    special: attack(
      'chi-special',
      'special',
      82,
      390,
      190,
      96,
      {
        startupMs: 150,
        activeMs: 190,
        recoveryMs: 240,
        cancelOpenMs: 0,
        cancelCloseMs: 0,
      },
      {
        juggleCost: 3,
        groundBounce: true,
        hitbox: { offsetX: 44, offsetY: -28, width: 120, height: 120 },
      },
    ),
  },
  animationStates: requiredAnimationStates,
};

export const PLAYABLE_CHARACTERS: CharacterDefinition[] = [heavyBrawler, technical, agile];

export const findCharacterById = (id: string): CharacterDefinition =>
  PLAYABLE_CHARACTERS.find((character) => character.id === id) ?? PLAYABLE_CHARACTERS[0];
