import type { EnemyDefinition } from './types';

export const ENEMY_DEFINITIONS: EnemyDefinition[] = [
  {
    id: 'enemy-brawler',
    enemyType: 'brawler',
    maxHp: 210,
    attack: 20,
    defense: 8,
    moveSpeed: 170,
    decisionMs: 900,
    approachRange: 360,
    retreatRange: 110,
    attackRange: 86,
    weight: 1,
    weapon: 'none',
  },
  {
    id: 'enemy-rusher',
    enemyType: 'rusher',
    maxHp: 160,
    attack: 16,
    defense: 6,
    moveSpeed: 240,
    decisionMs: 700,
    approachRange: 420,
    retreatRange: 80,
    attackRange: 72,
    weight: 0.8,
    weapon: 'none',
  },
  {
    id: 'enemy-tank',
    enemyType: 'tank',
    maxHp: 360,
    attack: 26,
    defense: 16,
    moveSpeed: 120,
    decisionMs: 1_100,
    approachRange: 320,
    retreatRange: 130,
    attackRange: 96,
    weight: 1.8,
    weapon: 'none',
  },
  {
    id: 'enemy-armed',
    enemyType: 'armed',
    maxHp: 250,
    attack: 24,
    defense: 10,
    moveSpeed: 160,
    decisionMs: 950,
    approachRange: 390,
    retreatRange: 120,
    attackRange: 110,
    weight: 1.1,
    weapon: 'bat',
  },
  {
    id: 'enemy-ranged',
    enemyType: 'ranged',
    maxHp: 190,
    attack: 22,
    defense: 7,
    moveSpeed: 145,
    decisionMs: 1_000,
    approachRange: 520,
    retreatRange: 200,
    attackRange: 280,
    weight: 0.9,
    weapon: 'gun',
  },
];

export const findEnemyById = (id: string): EnemyDefinition =>
  ENEMY_DEFINITIONS.find((enemy) => enemy.id === id) ?? ENEMY_DEFINITIONS[0];
